version: "3"
services: 
  react-app:
    image: sociality-frontend-docker
    stdin_open: true
    ports: 
      - "3000:3000"
    # networks: 
    #   - mern-app:

  api-server:
    image: sociality-backend-docker
    ports: 
      - "5000:5000"
    # networks: 
    #   - mern-app:
  #   depends_on: 
  #     - mongo
  
  # mongo:
  #   image: mongo:3.6.19-xenial
  #   ports: 
  #     - "27017:27017"
# networks: 
#   mern-app:
#     driver: bridge